name: Test and Build

on:
  push:
    branches:
      - master

jobs:
  test-and-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set Up
        uses: actions/setup-node@v2
        with:
          node-version: 18

      - name: Install
        run: npm i

      - name: Tests
        run: npm test

      - name: Build
        run: npm run build
